### ISSUE TITLE
index.html has invalid url for vs extension

### ISSUE THREAD

**Issue by k0st1x** [AvaloniaUI/avaloniaui.github.io#1]
there is
&lt;a href=&quot;https://visualstudiogallery.msdn.microsoft.com/87db356c-cec9-4a07-b7db-a4ed8a921ac9&quot;&gt;
but should be
&lt;a href=&quot;https://visualstudiogallery.msdn.microsoft.com/a4542e8a-b56c-4295-8df1-7e220178b873&quot; target=&quot;_blank&quot;&gt;

**Comment by kekekeks** [comment]
Fixed
